In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv('../drugs_cleaner.csv')
df.head()

,Unnamed: 0,ACCGDLN,AGE,AGECAT,ALTDUM,AMENDYR,AMTTOTAL,CASETYPE,CITWHERE,COMBDRG2,...,TOTUNIT.2,TOTUNIT.3,UNIT1,MWGT1,WGT1,XCRHISSR,XFOLSOR,XMAXSOR,XMINSOR,SENTRNGE
0,6,1.0,20.0,1.0,0,2018.0,0,1.0,211.0,6.0,...,1.0,1.0,1.0,NaN,NaN,1.0,17.0,30.0,24.0,8.0
1,14,1.0,64.0,8.0,0,2018.0,0,1.0,211.0,1.0,...,1.0,1.0,1.0,1193400.0,5967.00,3.0,27.0,108.0,87.0,0.0
2,15,1.0,28.0,3.0,0,2018.0,0,1.0,211.0,3.0,...,1.0,1.0,2.0,2000000.0,2000.00,6.0,27.0,162.0,130.0,2.0
3,26,2.0,55.0,7.0,0,2018.0,0,1.0,211.0,77.0,...,1.0,1.0,1.0,10300.0,4.12,5.0,13.0,37.0,30.0,0.0
4,29,1.0,30.0,3.0,0,2018.0,0,1.0,211.0,6.0,...,1.0,1.0,1.0,169200.0,84.60,6.0,25.0,137.0,110.0,2.0

In [10]:
df.columns = df.columns.str.lower()
df.drop(columns='unnamed: 0', inplace=True)
df.head()

,accgdln,age,agecat,altdum,amendyr,amttotal,casetype,citwhere,combdrg2,comdum,...,totunit.2,totunit.3,unit1,mwgt1,wgt1,xcrhissr,xfolsor,xmaxsor,xminsor,sentrnge
0,1.0,20.0,1.0,0,2018.0,0,1.0,211.0,6.0,0,...,1.0,1.0,1.0,NaN,NaN,1.0,17.0,30.0,24.0,8.0
1,1.0,64.0,8.0,0,2018.0,0,1.0,211.0,1.0,0,...,1.0,1.0,1.0,1193400.0,5967.00,3.0,27.0,108.0,87.0,0.0
2,1.0,28.0,3.0,0,2018.0,0,1.0,211.0,3.0,0,...,1.0,1.0,2.0,2000000.0,2000.00,6.0,27.0,162.0,130.0,2.0
3,2.0,55.0,7.0,0,2018.0,0,1.0,211.0,77.0,0,...,1.0,1.0,1.0,10300.0,4.12,5.0,13.0,37.0,30.0,0.0
4,1.0,30.0,3.0,0,2018.0,0,1.0,211.0,6.0,0,...,1.0,1.0,1.0,169200.0,84.60,6.0,25.0,137.0,110.0,2.0

In [13]:
df['prisdum'].value_counts(normalize=True)

1    0.955196
0    0.044804
Name: prisdum, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='prisdum')
y = df['prisdum']

X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,random_state=42)

In [15]:
def print_sampling_stats(X_train_df, X_train_sampled,
                         y_train, y_train_sampled,
                         y_test):
    
    print('Original dataset classes: {}'.format(Counter(y_train)))
    print('Resampled dataset classes: {}'.format(Counter(y_train_sampled)))
    print()
    print('Test dataset classes still the same to model real world: {}'.format(Counter(y_test)))

    print()
    print('X_train shape (under/reg): ', X_train_sampled.shape, X_train_df.shape)
    print('y_train shape (under/reg): ', y_train_sampled.shape, y_train.shape)
    print('X_test, shape y_test: ', X_test_df.shape, y_test.shape)

In [16]:
from imblearn.over_sampling import SMOTE

smo = SMOTE()
X_train_smo, y_train_smo = smo.fit_resample(X_train, y_train)


print_sampling_stats(X_train, X_train_smo,
                     y_train, y_train_smo,
                     y_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**To Do List**
1. Figure out how to fill missing values
2. Resampling of minor class with smote